
    Plant.create(name: 'blades leave', price: 100, image: 'images/1.faux_monstera_in_stone_painted_planter.jpg')
    Plant.create(name: 'naméspace', price: 200, image: 'images/017-large-decorative-flower-pots-cool-indoor-plants-plant-1w800-inside-for-remodel-2.jpg' )
    Plant.create(name: 'needles in water', price: 30, image:'images/61oVbbY6fSL._SR500,500_.jpg')
    Plant.create(name: 'osumazon', price: 80, image: 'images/3558f9bec47f67f41b3edbe1dbbea659.jpg')
    Plant.create(name: 'rapunzle', price: 85, image: 'images/38836d1b5da1e2a1a20ca27362b70adc.jpg')
    Plant.create(name: 'sid vicious', price: 110, image: 'images/88722-00-BAKI_20140901090429.jpg')
    Plant.create(name: 'steve zissou', price: 35, image: 'images/804870-03-2T.jpg')
    Plant.create(name: "idaho's best", price: 18, image: 'images/1452656406696.jpg')
    Plant.create(name: 'cookies & cream', price: 40, image: 'images/air-plant-wall-glass-terrarium-wall-bubble.jpg')
    Plant.create(name: 'jerold', price: 20, image: 'images/best-house-plants.jpg' )
    Plant.create(name: 'triangle down under', price: 30, image: 'images/har3_34004735-ce4f-463d-99c9-21fa15832325_580x@2x.jpg')
    Plant.create(name: 'mountains building', price: 25, image: 'images/images.crateandbarrel.jpg' )
    Plant.create(name: 'joanne', price: 30, image: 'images/indoor-cactus-cactus-for-desk-indoor-with-exclusive-ceramic-indoor-cactus-garden-decorating-ideas.jpg' )
    Plant.create(name: 'moon landing', price: 25, image: 'images/indoor-hanging-plants-264557-1533232476708-product.700x0c.jpg')
    Plant.create(name: 'joe lorenzo', price: 30, image:'images/indoor-plant-32-beautiful-house-that-are-also-easy-to-maintain-b-u-y-i-t-pot-name-and-picture-stand-low-light-planter-indium-bunning-melbourne.jpg' )
    Plant.create(name: 'waffels with decisions', price: 80, image: 'images/NorfolkIslandPine.jpg' )
    Plant.create(name: 'woods travelled', price: 80, image: 'images/peace-lily.jpg')
    Plant.create(name: 'horses and divorces', price: 50, image: 'images/SM-9.jpg' )
    Plant.create(name: 'camels on moonstones', price: 40, image: 'images/tall-house-plants-large-indoor-plants-tall-artificial-house-plants-uk.jpg' )
    Plant.create(name: 'festival of fyre', price: 5000, image: 'images/tumblr_o3uwkebUKw1ue7yrmo1_400.jpg' )
    Plant.create(name: 'midtown', price: 65, image: 'images/types-of-tall-house-plants-sale-common-tall-house-plants-common-tree-house-plants.jpg' )
